Support MonoDevelop 8.1
API change causing a method not found when attempting to open the full
IDE log file from the IDE Log Viewer pad window.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: void MonoDevelop.Ide.Gui.FileOpenInformation..ctor(MonoDevelop.Core.FilePath,MonoDevelop.Projects.Project)
  at MonoDevelop.LogMonitor.Gui.LogMonitorPad.OnOpenIdeLogButtonClick (System.Object sender, System.EventArgs e) [0x00001] in <38bd49806b48444e828565cb95c77b40>:0